apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: node-example
        image: kzettlmeier/node-example:v1.0.0
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 3000
          initialDelaySeconds: 3
          failureThreshold: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 3000
          initialDelaySeconds: 3
          failureThreshold: 3
          periodSeconds: 3